### INFO ON VARIABLES : https://github.com/Huachao/vscode-restclient
@baseUrl = http://localhost:3000/api
### Create the user james
POST {{baseUrl}}/users/
Content-Type: application/json

{
    "email":"james@cool.com",
    "password":"Jj"
}

###
POST {{baseUrl}}/users/
Content-Type: application/json

{
    "username": "juvanton",
    "email":"julien.vantongerloo@hotmail.com",
    "password": "Abc",
    "admin": true
}

###
@julienToken = {{login.response.body.token}}
PUT {{baseUrl}}/users/juvanton
Content-Type: application/json
Authorization: {{julienToken}}

{
    
    "username": "julien.vantongerloo@hotmail.com",
    "email":"julien.vantongerloo@hotmail.com",
    "password": "$2b$10$Kuu0OWetWBRvIT17VYxM5.cmj2wia9ZHrSofkRD2D4gs73T2sAwa2",
    "admin": true
}

###
DELETE {{baseUrl}}/users/test
Authorization: {{julienToken}}

### Define & request variable & Log the user james
# @name login
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email":"james@cool.com",
    "password":"Jj"
}

### get the token from previous request
@jamesToken = {{login.response.body.token}}

### View all films
GET {{baseUrl}}/films
Authorization: {{jamesToken}}

### Add a film
POST {{baseUrl}}/films/
Content-Type: application/json
Authorization: {{jamesToken}}

{
    "title":"Star Wars: The Phantom Menace (Episode I)",
    "duration": "136",
    "budget": "115000000",
    "link":"https://en.wikipedia.org/wiki/Star_Wars:_Episode_I_%E2%80%93_The_Phantom_Menace"
}

### Add another film
POST {{baseUrl}}/films/
Content-Type: application/json
Authorization: {{jamesToken}}

{
    "title":"Star Wars: Episode 2",
    "duration": "1",
    "budget": "11",
    "link":"findIt.com"
}

### Update film with ID == 2

PUT {{baseUrl}}/films/2
Content-Type: application/json
Authorization: {{jamesToken}}

{
    "title":"Star Wars: Episode 2",
    "duration": "11",
    "budget": "111",
    "link":"www.findIt.com"
}

### Delete the film with ID == 2
DELETE {{baseUrl}}/films/2
Authorization: {{jamesToken}}

### Read film with ID == 1
GET {{baseUrl}}/films/1
Authorization: {{jamesToken}}
